change sync test
Pepperi-Addons/health-monitor pull request #77
Opened 2023-09-03 13:42 UTC by MayTetro1

2023-09-05 06:21 UTC, roiaharon-pepperi requested changes

2023-09-05 06:21 UTC, roiaharon-pepperi commented on server-side/entities.ts
> +const syncUUID = '00000000-0000-0000-0000-000000abcdef';
@ido-pepperi  this is the wacd uuid, shouldn't it be the sync uuid?

2023-09-05 06:21 UTC, roiaharon-pepperi commented on server-side/sync_test.service.ts
> +        this.errorCode = await InternalSyncTest(this.systemHealthBody, this.client, this.monitorSettingsService, this.monitorSettings);
why is the InternalSyncTest isn't part of this class?

2023-09-06 15:39 UTC, ido-pepperi approved these changes

2023-09-06 15:39 UTC, merged